#########################################################
# Gradle                                                #
#########################################################
org.gradle.jvmargs=-Xmx4G \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED

#########################################################
# Minecraft Versions                                    #
#########################################################
mc_version=1.20.1
mc_range=[1.20,1.21)
forge_version=47.3.28
forge_version_range=[46,)
loader_version_range=[46,)

#########################################################
# Mapping Versions                                    #
#########################################################
mapping_channel=parchment
mapping_version=2023.09.03

#########################################################
# Provided APIs                                         #
#########################################################
crafttweaker_version=14.0.12
kubejs_version=2001.6.5-build.20
architectury_version=9.1.12
rhino_version=2001.2.2-build.6
curios_version=5.9.1+1.20.1
cou_version=5159193
projecte_version=4901949
mek_version=1.20.1-10.4.9.61
ae2_version=5565729
packagedauto_version=6932949
packagedavaritia_version=6980903
# Allow: jei, rei, emi
recipe_viewer=jei
jei_version=15.20.0.112
rei_version=12.1.785
emi_version=1.1.20+1.20.1
# Allow: wthit, jade, top
runtime_tooltip_mod=jade
wthit_version=8.1.0
jade_id=4986594
top_version=9.0.0

#########################################################
# Third party dependencies                              #
#########################################################
junit_version=5.10.0-M1
lombok_version=1.18.+
mixin_extras_version=0.4.1
mixin_version=0.8.5

#########################################################
# Mod Properties                                        #
#########################################################
mod_id=keneng
mod_name=Kenergy Engineering
mod_platform=forge
mod_license=MIT
mod_version=1.0.0
mod_version_tag=release
mod_group_id=committee.nova.mods
mod_authors=cnlimiter, cm, MHanHanBing
mod_description=
issue_tracker=https://github.com/Nova-Committee/Kenergy Engineering/issues
pack_format_number=15